# Generated by Django 6.1 on 2026-09-15 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_statushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('hr_screen', 'HR Screen'), ('hiring_manager', 'Hiring Manager'), ('technical', 'Technical'), ('take_home_review', 'Take-home Review'), ('final', 'Final'), ('other', 'Other')], default='hr_screen', max_length=30)),
                ('mode', models.CharField(choices=[('video', 'Video'), ('phone', 'Phone'), ('onsite', 'On-site'), ('other', 'Other')], default='video', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('outcome', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='application.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
