# Generated by Django 6.1 on 2026-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_applicationdocument_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20),
        ),
    ]
