# Generated by Django 6.1 on 2026-09-17 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_jobapplication_currency_jobapplication_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='interview',
            name='location_or_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('remote', 'Remote')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__gte', 0), ('salary_min__isnull', True), _connector='OR'), name='application_salary_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('salary_max__gte', 0), ('salary_max__isnull', True), _connector='OR'), name='application_salary_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_max__gte', models.F('salary_min')), _connector='OR'), name='application_salary_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('application_date__isnull', True), ('deadline__isnull', True), ('deadline__gte', models.F('application_date')), _connector='OR'), name='application_deadline_not_before_date'),
        ),
    ]
