# Generated by Django 6.1 on 2026-09-17 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_interview_interviewer_interview_location_or_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2, 'Company name must be at least 2 characters.')]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(max_length=160, validators=[django.core.validators.MinLengthValidator(2, 'Job title must be at least 2 characters.')]),
        ),
    ]
