# Generated by Django 6.1 on 2026-09-17 06:56

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_jobapplication_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateField(error_messages={'blank': 'Application date is required.'}, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.CharField(max_length=120, validators=[application.models.validate_company_name]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(max_length=160, validators=[application.models.validate_job_title]),
        ),
    ]
