# Generated by Django 6.1 on 2026-09-21 12:17

import re
from decimal import Decimal, InvalidOperation

import django.core.validators
from django.db import migrations, models


LEGACY_SALARY_PATTERN = re.compile(
    r'^\s*(?P<symbol>[\u20ac\u00a3])?\s*'
    r'(?P<minimum>\d+(?:[.,]\d{1,2})?)'
    r'(?:\s*(?:-|\u2013)\s*(?P<maximum>\d+(?:[.,]\d{1,2})?))?'
    r'\s*(?P<code>[A-Za-z]{3})?\s*$'
)
SYMBOL_CURRENCIES = {
    '\u20ac': 'EUR',
    '\u00a3': 'GBP',
}


def migrate_legacy_salaries(apps, schema_editor):
    JobApplication = apps.get_model('application', 'JobApplication')

    for application in JobApplication.objects.exclude(salary=''):
        if application.salary_min is not None or application.salary_max is not None:
            continue

        match = LEGACY_SALARY_PATTERN.fullmatch(application.salary)

        if not match:
            continue

        symbol_currency = SYMBOL_CURRENCIES.get(match.group('symbol'))
        currency_code = (match.group('code') or '').upper()

        if symbol_currency and currency_code and symbol_currency != currency_code:
            continue

        try:
            minimum = Decimal(match.group('minimum').replace(',', '.'))
            maximum_text = match.group('maximum')
            maximum = Decimal(maximum_text.replace(',', '.')) if maximum_text else None
        except InvalidOperation:
            continue

        if maximum is not None and maximum < minimum:
            continue

        application.salary_min = minimum
        application.salary_max = maximum
        application.currency = currency_code or symbol_currency or application.currency or 'EUR'
        application.save(update_fields=['salary_min', 'salary_max', 'currency'])


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_jobapplication_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, validators=[django.core.validators.RegexValidator(message='Enter a three-letter currency code, such as EUR or USD.', regex='^[A-Za-z]{3}$')]),
        ),
        migrations.RunPython(migrate_legacy_salaries, migrations.RunPython.noop),
    ]
