# Generated by Django 6.1 on 2026-09-21 18:51

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_jobapplication_recruiter_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=application.models.document_upload_path, validators=[application.models.validate_document_file]),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover Letter'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('other', 'Other')], default='cv', max_length=30),
        ),
    ]
