# Generated by Django 6.1 on 2026-09-21 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_applicationdocument_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.CreateModel(
            name='RequestThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('identifier_hash', models.CharField(max_length=64)),
                ('window_started', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['window_started'], name='request_throttle_window_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'identifier_hash'), name='request_throttle_scope_identifier_unique')],
            },
        ),
    ]
