# Generated by Django 6.1 on 2026-10-01 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_applicationdocument_notes_and_more'),
    ]

    operations = [
        # Validation and Python defaults change; the database column does not.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='jobapplication',
                    name='currency',
                    field=models.CharField(blank=True, default='', max_length=3, validators=[django.core.validators.RegexValidator(message='Enter a three-letter currency code, such as EUR or USD.', regex='^[A-Za-z]{3}$')]),
                ),
            ],
        ),
    ]
